### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by fieu** [AdriaanBoshoff/RustCentralBanServer#1]
Hi, I am developing the same type of project, but in Go.

I was wondering, how did you find that the Rust server sends a POST request when someone is banned?

I ask because it's not mentioned anywhere on the Rust wiki: https://wiki.facepunch.com/rust/centralized-banning

There is only the information on how to retrieve a ban.

**Comment by AdriaanBoshoff** [comment]
Hi, Rust does not send a post request when someone gets banned. The server only does a get request to check if someone is banned. Thats all. The post request is for other developers if they want to add bans.

**Comment by fieu** [comment]
Oh I didn't realize that. So when a server bans someone nothing happens? I would have to make a plugin server side for it to save the ban?

**Comment by AdriaanBoshoff** [comment]
> Oh I didn't realize that. So when a server bans someone nothing happens? I would have to make a plugin server side for it to save the ban?

To my knowledge yes.

**Comment by fieu** [comment]
Okay, good to know.

Thanks for taking the time to respond, I'll close the issue now. 😄
